name: .NET CI/CD

on:
  push:       # à chaque push
  pull_request: # et à chaque PR

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test --no-build --configuration Release --filter Category!=Performance --logger "trx;LogFileName=test-results.trx"

    - name: Publish app
      run: dotnet publish -c Release -o ./publish

    - name: Upload artifacts (build + test results)
      uses: actions/upload-artifact@v5
      with:
        name: tourguide-artifacts
        path: |
          ./publish
          **/TestResults/*.trx
